### ISSUE TITLE
Test suite

### ISSUE THREAD

**Issue by leodido** [fabbricadigitale/paper-chip#1]

**Comment by alelb** [comment]
I'm working on a web-component-tester suite for paper-chip and paper-chip-input.

**Comment by leodido** [comment]
:+1

**Comment by leodido** [comment]
We should review all test cases and, preferably, also test visual coherence of the component.

**Comment by leodido** [comment]
We should evaluate:

- [phantomcss](https://github.com/Huddle/PhantomCSS) - image diffs
- [csscritic](https://github.com/cburgmer/csscritic)

**Comment by leodido** [comment]
I am satisfied for now, closing.
