### ISSUE TITLE
Improve tests

### ISSUE THREAD

**Issue by leodido** [fabbricadigitale/paper-chip#14]
## Self remove feature

Target: `<paper-chip>`.

- [x] test that its disconnect callback is called when the element self removes itself
- [x] test that the elements is not in the parentElement's DOM anymore when it removes itself

**Comment by alelb** [comment]
@leodido I wrote the following test to check that disconnectedCallback is called

```js
test('disconnect callback of paper-chip has been called', (done) => {
    let chip = fixture('disc')
    const disconnectedCallback = sinon.spy(chip, 'disconnectedCallback');
    chip.$.removeBtn.click()
    expect(disconnectedCallback).to.have.been.called;
    done()            
})
```
It fails with the message:
```bash
Error: expected disconnectedCallback to have been called at least once, but it was never called
  Context.test at paper-chip.html:105
```

What's wrong with my test?
