### ISSUE TITLE
paper-chip style in Firefox broken

### ISSUE THREAD

**Issue by mbierlee** [fabbricadigitale/paper-chip#25]
In the latest Firefox paper-chip's style is broken. Icons don't properly render anymore, labels aren't truncated like they are in chrome and the secondary line (the caption) is always visible.

This can easily be seen when opening the demo in Firefox

Firefox 54.0 (64-bit) on Fedora Linux

**Comment by leogr** [comment]
Good catch!

<img width="438" alt="screen shot 2017-07-17 at 16 40 11" src="https://user-images.githubusercontent.com/3390997/28273433-b0d19d0a-6b0e-11e7-8bf6-625e02eb1cde.png">
<img width="361" alt="screen shot 2017-07-17 at 16 39 51" src="https://user-images.githubusercontent.com/3390997/28273439-b1e0d864-6b0e-11e7-92d7-b45d18def930.png">

**Comment by leogr** [comment]
I seems to be related to https://github.com/Polymer/polymer/issues/4463

I'm going to fix that.
