### ISSUE TITLE
Underline not visible

### ISSUE THREAD

**Issue by mbierlee** [fabbricadigitale/paper-chip#30]
In normal material design and paper elements a colored underline is visible beneath the input element. For some reason however it has been hidden in paper-chip-input:

`--paper-input-container-underline: {
    display: none;
}
;`

Why is this? Some people prefer to show it, especially when using it on forms where other paper inputs are present as well. Wouldn't it be better to make it configurable, either by passing on a CSS mixin like paper container does or through a property?

**Comment by alelb** [comment]
Hi @mbierlee, thanks for noticing it, you're right. We must to make it configurable.

We'll include fixes to material design in next version. 

If you want to do a PR you're welcome!
