### ISSUE TITLE
Chip sizing and overflow differs between browsers

### ISSUE THREAD

**Issue by mbierlee** [fabbricadigitale/paper-chip#31]
The default chip sizing and label overflow differs slightly between Firefox and Chrome. In Chrome there seems to be a right-most padding and the label cuts off into ellipses at some point. These characteristics are absent in Firefox.

Firefox:
![chipsfirefox](https://user-images.githubusercontent.com/1678927/28310863-166f0a90-6bae-11e7-99e0-1df4ebdabb54.png)

Chrome:
![chipschrome](https://user-images.githubusercontent.com/1678927/28310869-1b4d5d3c-6bae-11e7-8dc3-5f980e8aa61f.png)

Code:
```html
<div>
    <paper-chip>
        <div slot="label" class="label">Short</div>
    </paper-chip>
    <paper-chip>
        <div slot="label" class="label">Slightly Longer</div>
    </paper-chip>
</div>
```

Chrome 59.0.3071.115 (Official Build) (64-bit)
Firefox 54.0 (64-bit)
On Fedora Linux

**Comment by alelb** [comment]
Hi @mbierlee thanks for your notice,

the css selector `:host(*:not([removable])) #label ::slotted([slot="label"])` doesn't work on Firefox.
The issue seem solved if I use `:host(:not([removable])) #label ::slotted([slot="label"])` selector.

A patch coming soon.
