### ISSUE TITLE
Input must fill remaining space

### ISSUE THREAD

**Issue by alelb** [fabbricadigitale/paper-chip#37]

**Comment by leodido** [comment]
I agree. Anyway we could encounter difficulties making this since the paper-input-container does not provide CSS mixin to change the flex horizontal layout and the flex properties of its children (`#prefix`, `#labelAndInput...`, `#suffix`).

**Comment by alelb** [comment]
Implicitly solved by 7550eecc5eff2179bc41a3afb8c7cdc2d8a3c8ab.
