### ISSUE TITLE
Input elements in content slot break blur functionality

### ISSUE THREAD

**Issue by wvanteijlingen** [fabbricadigitale/paper-chip#42]
**Element:** paper-chip

**Problem**
If you have for example a paper-icon-button in the content slot it's impossible to register the on-tap event for the button. 

**Steps to reproduce**
1) Create a content slot with for example a paper-icon-button
2) Click on the paper-icon-button

**Cause**
The _onBlur event fires when the focus changes to your paper-icon-button. 

**Hackish solution**

```
            _onBlur(event) {
                let relatedTarget = event.relatedTarget || null;
                if (relatedTarget !== null) {
                    let parent = relatedTarget.parentElement;
                    while ((parent || null) !== null) {
                        if (parent === this) {
                            return;
                        }
                        parent = parent.parentElement;
                    }
                }
                this.opened = false;
            }
```
It's definitely not a feasible solution because it is impossible to blur the paper-chip if your input element has focus.

**Comment by leogr** [comment]
@wvanteijlingen any chance you could make a PR?

**Comment by leogr** [comment]
Hi @wvanteijlingen ,
we've added a test and refactored your PRs with a definitive solution, that has been merged (we're going to release a new version).

Let us know if that works as expected and thanks for your contribution!

**Comment by wvanteijlingen** [comment]
Hi @leogr 

Sure, no problem! Works as expected, thanks.
