### ISSUE TITLE
How to enable pre-fill paper-chip on autocomplete?

### ISSUE THREAD

**Issue by alkunjo** [fabbricadigitale/paper-chip#60]
Can we have pre-fill or set default `paper-chip` item inside `paper-chip-input` using data binding?
for example like this:
```
<paper-chip-input id="rcListAndInput" label="Another Category" datasource="[[dataOtherRc.rows]]">
  <template is="dom-repeat" items="[[dataRc.rows]]" as="rc">
      <paper-chip id="exist-item">
        <span slot="label" class="label">[[rc.RestCategory.name]]</span>
      </paper-chip>
  </template>
</paper-chip-input>
```

**Comment by ndormont** [comment]
Hey @alkunjo , you can do this by injecting an object (or multiple) in the `paper-chip-input` attribute `values`. Do you absolutely have to use the `dom-repeat` template ?

**Comment by alkunjo** [comment]
No, it's not a must for me to use `dom-repeat`. Thank you for the insight. Your solution works like a charm :smile: :+1:
