### ISSUE TITLE
paper-chip styling on hover doesn't work

### ISSUE THREAD

**Issue by alkunjo** [fabbricadigitale/paper-chip#64]
I'm trying to give custom styling on my `paper-chip` for example like below. But it seems doesn't work. Is there any mistakes on my style or it is not supported yet?

```
paper-chip:hover{
    cursor: pointer;
    --paper-chip-background-color: #fbce9a;
}
```
![paper-chip-hover](https://user-images.githubusercontent.com/9002652/33870880-a8a17de6-df42-11e7-8842-a4cc779502f0.gif)

**Comment by alelb** [comment]
Hi @alkunjo, your code seems work.

![hover](https://user-images.githubusercontent.com/22765346/34102904-0c113946-e3eb-11e7-8534-2d32b2686e50.gif)

Are standalone chips or inside a `paper-chip-input` element?

**Comment by alkunjo** [comment]
Hai @alelb, thank you for replying my question. I use those `paper-chip` on `dom-repeat` with data binding that I get from an `iron-ajax` call. I just checked my code and found my mistake. I need to specify the `paper-chip` with an `id` and when it's hovered, it changes the color. Thank you, I'll close the issue
