### ISSUE TITLE
Code review about autocomplete feature

### ISSUE THREAD

**Issue by alelb** [fabbricadigitale/paper-chip#9]

**Comment by leodido** [comment]
I propose to merge `<paper-chip-input-autocomplete>` within `<paper-chip-input>` providing to this one a boolean property `autocomplete`.

Another option (please think about it) would be to make the `autocomplete` property as the data source (and implicitly the activator, too) of the autocomplete feature.

**Comment by leogr** [comment]
@leodido I agree, also for the last option. 
However, we have to pay attention to do not violate SRP. We can go on this way now and maybe a day we'll move the autocomplete logic away from here.

**Comment by leodido** [comment]
@leogr yes.

Infact I think a better option would be to create an **autocomplete only component/mixin**, and then compose it with the `<paper-chip-input>`.

Are we sure such mixin/component does not exists already?

**Comment by leogr** [comment]
I've looked for it but no luck. Furthermore, all [published components about autocomplete](https://www.webcomponents.org/search/autocomplete) seem to be very coupled.

**Comment by leodido** [comment]
Closing for now.
